[package]
name = "ex_1_19"
version = "0.1.0"
authors = ["Marcel Matz <mail@marcelmatz.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
